### ISSUE TITLE
Error adding url to battlescribe

### ISSUE THREAD

**Issue by Count0Int** [MrJacob252/reigninhell#1]
When I add the url for this to battlescribe, it just crashes out battlescribe and nothing is imported.  Is this repo working yet, or is it still in progress? 

Cheers!

**Comment by MrJacob252** [comment]
I should warn about this in the description, thanks for notifying me.

It's still WIP and there is a possibility I'll have to remake it completely. I wasn't able to correctly (aka at all) implement Battlescribe workflow so that's probably the main reason it does't work.

There should be no problem if you download the two BS files and import them manually from a file. 

Just a heads up, I've only implemented list-building for one-off games so there are no relics and essences for non-leaders, that you can get in the campaign.

I don't have much time fixing it now but it's on my TO DO list. If you'll find anything else definitely let me know.

**Comment by Count0Int** [comment]
Sounds good, thanks for the quick reply.   I will let you know if I find anything.
